# Generated by Django 4.2.7 on 2024-02-03 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatunekUzytkownika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoria', models.CharField(blank=True, max_length=255, null=True)),
                ('nazwa', models.CharField(max_length=255)),
                ('gestosc', models.FloatField()),
                ('Aluminum', models.CharField(blank=True, max_length=20, null=True)),
                ('Boron', models.CharField(blank=True, max_length=20, null=True)),
                ('Carbon', models.CharField(blank=True, max_length=20, null=True)),
                ('Chromium', models.CharField(blank=True, max_length=20, null=True)),
                ('Copper', models.CharField(blank=True, max_length=20, null=True)),
                ('Cobalt', models.CharField(blank=True, max_length=20, null=True)),
                ('Iron', models.CharField(blank=True, max_length=20, null=True)),
                ('Manganese', models.CharField(blank=True, max_length=20, null=True)),
                ('Nickel', models.CharField(blank=True, max_length=20, null=True)),
                ('Phosphorus', models.CharField(blank=True, max_length=20, null=True)),
                ('Silicon', models.CharField(blank=True, max_length=20, null=True)),
                ('Vanadium', models.CharField(blank=True, max_length=20, null=True)),
                ('Tungsten', models.CharField(blank=True, max_length=20, null=True)),
                ('Molybdenum', models.CharField(blank=True, max_length=20, null=True)),
                ('Niobium', models.CharField(blank=True, max_length=20, null=True)),
                ('Titanium', models.CharField(blank=True, max_length=20, null=True)),
                ('Sulfur', models.CharField(blank=True, max_length=20, null=True)),
                ('Zirconium', models.CharField(blank=True, max_length=20, null=True)),
                ('informacje_dodatkowe', models.TextField(blank=True, max_length=500, null=True)),
                ('TensileStrengthUltimate', models.FloatField(blank=True, null=True)),
                ('TensileStrengthYield', models.FloatField(blank=True, null=True)),
                ('ElongationAtBreak', models.FloatField(blank=True, null=True)),
                ('ModulusOfElasticity', models.FloatField(blank=True, null=True)),
                ('ReductionOfArea', models.FloatField(blank=True, null=True)),
                ('HardnessRockwellB', models.FloatField(blank=True, null=True)),
                ('HardnessBrinell', models.FloatField(blank=True, null=True)),
                ('HardnessKnoop', models.FloatField(blank=True, null=True)),
                ('stworzony_przez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stworzone_gatunki_uzytkownika', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Gatunek Użytkownika',
            },
        ),
    ]
