# Generated by Django 4.2.7 on 2024-02-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatunekuzytkownika',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
