# Generated by Django 4.2.7 on 2024-02-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownik', '0002_gatunekuzytkownika_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatunekuzytkownika',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
