# Generated by Django 4.2.7 on 2024-02-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownik', '0004_alter_gatunekuzytkownika_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatunekuzytkownika',
            name='kategoria',
        ),
    ]
