# Generated by Django 4.2.7 on 2024-02-08 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strona_glowna', '0009_gatunek_stworzony_przez'),
        ('uzytkownik', '0005_remove_gatunekuzytkownika_kategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatunekuzytkownika',
            name='kategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gatunki_uzytkownika', to='strona_glowna.kategorie'),
        ),
    ]
