# Generated by Django 4.2.7 on 2024-02-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownik', '0006_gatunekuzytkownika_kategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatunekuzytkownika',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
