# Generated by Django 4.2.7 on 2024-01-11 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaneSkladuChemicznego',
            fields=[
                ('Id_składu_chemicznego', models.AutoField(
                    primary_key=True, serialize=False)),
                ('Aluminum', models.CharField(blank=True, max_length=20, null=True)),
                ('Boron', models.CharField(blank=True, max_length=20, null=True)),
                ('Carbon', models.CharField(blank=True, max_length=20, null=True)),
                ('Chromium', models.CharField(blank=True, max_length=20, null=True)),
                ('Copper', models.CharField(blank=True, max_length=20, null=True)),
                ('Cobalt', models.CharField(blank=True, max_length=20, null=True)),
                ('Iron', models.CharField(blank=True, max_length=20, null=True)),
                ('Manganese', models.CharField(blank=True, max_length=20, null=True)),
                ('Nickel', models.CharField(blank=True, max_length=20, null=True)),
                ('Phosphorus', models.CharField(
                    blank=True, max_length=20, null=True)),
                ('Silicon', models.CharField(blank=True, max_length=20, null=True)),
                ('Vanadium', models.CharField(blank=True, max_length=20, null=True)),
                ('Tungsten', models.CharField(blank=True, max_length=20, null=True)),
                ('Molybdenum', models.CharField(
                    blank=True, max_length=20, null=True)),
                ('Niobium', models.CharField(blank=True, max_length=20, null=True)),
                ('Titanium', models.CharField(blank=True, max_length=20, null=True)),
                ('Sulfur', models.CharField(blank=True, max_length=20, null=True)),
                ('Zirconium', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DaneWlasciwosciFizycznych',
            fields=[
                ('Id_właściwości_fizycznych', models.AutoField(
                    primary_key=True, serialize=False)),
                ('Density', models.FloatField()),
                ('DensityUnit', models.CharField(max_length=10)),
                ('LinearMoldShrinkageStart',
                 models.FloatField(blank=True, null=True)),
                ('LinearMoldShrinkageEnd', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DaneWlasciwosciMechanicznych',
            fields=[
                ('Id_właściwości_mechanicznych', models.AutoField(
                    primary_key=True, serialize=False)),
                ('TensileStrengthUltimateStart',
                 models.FloatField(blank=True, null=True)),
                ('TensileStrengthUltimateEnd',
                 models.FloatField(blank=True, null=True)),
                ('TensileStrengthUltimateUnit', models.CharField(
                    blank=True, max_length=10, null=True)),
                ('TensileStrengthYieldStart',
                 models.FloatField(blank=True, null=True)),
                ('TensileStrengthYieldEnd', models.FloatField(blank=True, null=True)),
                ('TensileStrengthYieldUnit', models.CharField(
                    blank=True, max_length=10, null=True)),
                ('ElongationAtBreak', models.FloatField(blank=True, null=True)),
                ('ElongationAtBreakUnit', models.CharField(
                    blank=True, max_length=10, null=True)),
                ('ModulusOfElasticity', models.FloatField(blank=True, null=True)),
                ('ModulusOfElasticityUnit', models.CharField(
                    blank=True, max_length=10, null=True)),
                ('ReductionOfArea', models.FloatField(blank=True, null=True)),
                ('ReductionOfAreaUnit', models.CharField(
                    blank=True, max_length=10, null=True)),
                ('HardnessRockwellB', models.FloatField(blank=True, null=True)),
                ('HardnessBrinell', models.FloatField(blank=True, null=True)),
                ('HardnessBrinellUnit', models.CharField(
                    blank=True, max_length=10, null=True)),
                ('HardnessKnoop', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Komentarze',
            fields=[
                ('Id_komentarza', models.AutoField(
                    primary_key=True, serialize=False)),
                ('Komentarz', models.TextField()),
                ('Aplikacje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('Id_gatunku', models.AutoField(primary_key=True, serialize=False)),
                ('gatunek', models.CharField(max_length=255)),
                ('komentarze', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='strona_glowna.komentarze')),
                ('sklad_chemiczny', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='strona_glowna.daneskladuchemicznego')),
                ('wlasciwosci_fizyczne', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='strona_glowna.danewlasciwoscifizycznych')),
                ('wlasciwosci_mechaniczne', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='strona_glowna.danewlasciwoscimechanicznych')),
            ],
        ),
    ]
