# Generated by Django 4.2.7 on 2024-01-25 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strona_glowna', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gatunek',
            old_name='sklad_chemiczny',
            new_name='Id_składu_chemicznego',
        ),
        migrations.RenameField(
            model_name='gatunek',
            old_name='wlasciwosci_fizyczne',
            new_name='Id_właściwości_fizycznych',
        ),
        migrations.RenameField(
            model_name='gatunek',
            old_name='wlasciwosci_mechaniczne',
            new_name='Id_właściwości_mechanicznych',
        ),
        migrations.RemoveField(
            model_name='gatunek',
            name='komentarze',
        ),
        migrations.AddField(
            model_name='gatunek',
            name='Id_komentarza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='strona_glowna.komentarze'),
        ),
        migrations.AlterField(
            model_name='komentarze',
            name='Aplikacje',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='komentarze',
            name='Komentarz',
            field=models.TextField(null=True),
        ),
    ]
