# Generated by Django 4.2.7 on 2024-01-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona_glowna', '0002_rename_sklad_chemiczny_gatunek_id_składu_chemicznego_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatunek',
            name='Id_komentarza',
        ),
    ]
