# Generated by Django 4.2.7 on 2024-01-25 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strona_glowna', '0003_remove_gatunek_id_komentarza'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatunek',
            name='Id_komentarza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='strona_glowna.komentarze'),
        ),
    ]
