# Generated by Django 4.2.7 on 2024-01-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona_glowna', '0004_gatunek_id_komentarza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danewlasciwoscifizycznych',
            name='LinearMoldShrinkageEnd',
        ),
        migrations.RemoveField(
            model_name='danewlasciwoscifizycznych',
            name='LinearMoldShrinkageStart',
        ),
        migrations.RemoveField(
            model_name='danewlasciwoscimechanicznych',
            name='TensileStrengthUltimateEnd',
        ),
        migrations.RemoveField(
            model_name='danewlasciwoscimechanicznych',
            name='TensileStrengthUltimateStart',
        ),
        migrations.RemoveField(
            model_name='danewlasciwoscimechanicznych',
            name='TensileStrengthYieldEnd',
        ),
        migrations.RemoveField(
            model_name='danewlasciwoscimechanicznych',
            name='TensileStrengthYieldStart',
        ),
        migrations.AddField(
            model_name='danewlasciwoscimechanicznych',
            name='TensileStrengthUltimate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='danewlasciwoscimechanicznych',
            name='TensileStrengthYield',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
