# Generated by Django 4.2.7 on 2024-01-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strona_glowna', '0005_remove_danewlasciwoscifizycznych_linearmoldshrinkageend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
            ],
        ),
    ]
