# Generated by Django 4.2.7 on 2024-01-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strona_glowna', '0006_kategorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daneskladuchemicznego',
            options={'verbose_name_plural': 'Skład chemiczny'},
        ),
        migrations.AlterModelOptions(
            name='danewlasciwoscifizycznych',
            options={'verbose_name_plural': 'Właściwości fizyczne'},
        ),
        migrations.AlterModelOptions(
            name='danewlasciwoscimechanicznych',
            options={'verbose_name_plural': 'Właściwości mechaniczne'},
        ),
        migrations.AlterModelOptions(
            name='gatunek',
            options={'verbose_name_plural': 'Gatunki'},
        ),
        migrations.AlterModelOptions(
            name='kategorie',
            options={'ordering': ('nazwa',), 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='komentarze',
            options={'verbose_name_plural': 'Komentarze'},
        ),
    ]
