# Generated by Django 4.2.7 on 2024-02-01 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strona_glowna', '0008_gatunek_kategoria_alter_gatunek_id_komentarza'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatunek',
            name='stworzony_przez',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stworzone_gatunki', to=settings.AUTH_USER_MODEL),
        ),
    ]
